export default {
    name:'contact',
    title:'Contact',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'email',
            title:'Email',
            type:'string'
        },
        {
            name:'whatsapp',
            title:'Whatsapp',
            type:'string'
        },
        {
            name:'instagram',
            title:'Instagram',
            type:'string'
        },
        {
            name:'message',
            title:'Message',
            type:'text'
        }
    ]
}